### ISSUE TITLE
No two-way-binding for value?

### ISSUE THREAD

**Issue by arohr** [btecu/ember-select#1]
I expected `x-select` to listen to external value changes. In

`{{x-select model=repeatOptions value=selectedRepeat onSelect=(action 'selectRepeat')}}`

If I reset `selectedRepeat` to its default value externally, I would expect that the select-box to change to that default value. How can this be achieved?

**Comment by btecu** [comment]
Currently is not supported.
I've been avoiding the use of observers (which is the obvious solution).
I think it might be possible to be accomplished with `didUpdateAttrs` hook.

**Comment by btecu** [comment]
@arohr Latest release (0.1.3) supports value updates.

**Comment by arohr** [comment]
Very nice!
Thank you very much.

**Comment by Skgtouch** [comment]
This issue still persist in release (0.4.0)

**Comment by btecu** [comment]
@Skgtouch Open a new issue with a reproduction and try to use the latest release.
