### ISSUE TITLE
Placeholder attribute not adding in DOM in IE11 while adding in Chrome

### ISSUE THREAD

**Issue by Skgtouch** [btecu/ember-select#13]
Code 
```
{{x-select
      model=roleDropdownOptions
      onSelect=(action 'selectRole' (route-action 'onRoleSelected'))
      placeholder='Role'
      value=selectedRole
      valueKey='value'                    
}}
```

Despite of placeholder added here.
Placeholder attribute is not adding in dom in IE11.
![image](https://user-images.githubusercontent.com/9603887/37077458-18263cb4-2201-11e8-8545-a7b071c00293.png)

While it's coming in Chrome 
![image](https://user-images.githubusercontent.com/9603887/37077478-30deb10a-2201-11e8-8227-0e042b0919ad.png)

**Comment by btecu** [comment]
What version are you using?

**Comment by Skgtouch** [comment]
"ember-select": "^0.3.2",

**Comment by btecu** [comment]
It was fixed in `0.4.0`: https://github.com/btecu/ember-select/releases/tag/0.4.0

Can you confirm?

**Comment by Skgtouch** [comment]
Thnaks for the response. Will there be any breaking change if update the version of ember-select to `0.4.0` ?

**Comment by btecu** [comment]
There shouldn't be.

**Comment by Skgtouch** [comment]
Thanks! It worked :+1:
