### ISSUE TITLE
Update node dependency for node 13.*

### ISSUE THREAD

**Issue by Ralica** [btecu/ember-select#28]
Hello and thank you for sharing this wonderful add-on! :)

Could you fix the dependency to node so it does not limit it up to 12.*? 
Here is the error I see in the terminal when I run yarn:
ember-select@0.7.4: The engine "node" is incompatible with this module. Expected version "8.* || 10.* || 12.*". Got "13.5.0"

Cheers!

**Comment by btecu** [comment]
Hey, would you be able to submit a pull request?

**Comment by Ralica** [comment]
Sure

**Comment by btecu** [comment]
Updated in https://github.com/btecu/ember-select/pull/29 and released in `0.7.5`.
