### ISSUE TITLE
didUpdateAttrs with parameters is deprecated

### ISSUE THREAD

**Issue by ladadeedee** [btecu/ember-select#9]
https://emberjs.com/deprecations/v2.x/#toc_arguments-in-component-lifecycle-hooks

**Comment by btecu** [comment]
This was mentioned here: https://github.com/btecu/ember-select/pull/7

**Comment by btecu** [comment]
Fixed in `0.3.0` (https://github.com/btecu/ember-select/commit/cba60467ce0ee7940be2cdbb42070cdaf28d5b64).
